"""empty message

Revision ID: dd45040e2ad3
Revises: b88bcf94c1e7
Create Date: 2020-09-10 17:55:23.138617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd45040e2ad3'
down_revision = 'b88bcf94c1e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('from_recipe_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'recipes', 'recipes', ['from_recipe_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipes', type_='foreignkey')
    op.drop_column('recipes', 'from_recipe_id')
    # ### end Alembic commands ###
