"""empty message

Revision ID: fa9eff94de7b
Revises: 18e06a9b00de
Create Date: 2020-09-28 22:03:49.707484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa9eff94de7b'
down_revision = '18e06a9b00de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'collections', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'collections', type_='foreignkey')
    # ### end Alembic commands ###
