"""empty message

Revision ID: df2e1a12044f
Revises: dd45040e2ad3
Create Date: 2020-09-11 09:38:23.951751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df2e1a12044f'
down_revision = 'dd45040e2ad3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipes', 'image_src',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipes', 'image_src',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
